### ISSUE TITLE
Concatenating a scalar to a CuArray gives an Array

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#1162]
```julia
vcat(0.2,CuArray([0.2,0.2])) # Vector{Float64}
```

Seems like that should try to stay on the GPU?

**Comment by maleadt** [comment]
The current Base implementation of `cat` looks at the first argument to decide the output type: https://github.com/JuliaLang/julia/blob/690517a1e90e03f32a47b6881f53c2739f82f901/base/abstractarray.jl#L1709

Putting the scalar at the end does work, because we then get `cat_similar` called on the CuArray:

```
julia> vcat(CuArray([0.2,0.2]),0.2)
3-element CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}:
 0.2
 0.2
 0.2
```

So it seems like the Base abstraction isn't really made to solve this. There's a bunch of non-general workarounds in both Base (e.g. for `hcat` of adjoints) and StaticArrays (only for `vcat`), so I assume we can ass some similar ones to GPUArrays. It'll be limited to two-argument `vcat` and `hcat` though, but I guess that's the most common invocation anyway.
