### ISSUE TITLE
CUDA.jl tries to load CUDA compat loaded via jll even though system package is installed

### ISSUE THREAD

**Issue by oschulz** [JuliaGPU/CUDA.jl#1216]
I'm running a shifter container on NERSC Perlmutter (NVIDIA A100), based on "nvidia/cuda:11.3.1-cudnn8-devel-centos7". Perlmutter currently runs driver version 450.162, which seems to cause CUDA.jl to install and load CUDA_compat_jll. That doesn't work though, since the container image is read only. The image does contain the "cuda-compat-11-3-465" system package though, so CUDA_compat_jll shouldn't be necessary.

Could CUDA.jl try to use the system CUDA compat when `JULIA_CUDA_USE_BINARYBUILDER="false"`?

**Comment by maleadt** [comment]
> The image does contain the "cuda-compat-11-3-465" system package though, so CUDA_compat_jll shouldn't be necessary.

That will only give you a CUDA 11.3-compatible driver library, whereas CUDA.jl generally prefers the most recent one possible (the Compat JLL gives a 11.4 driver).

`JULIA_CUDA_USE_BINARYBUILDER` is different, because that is for the lazily downloaded CUDA toolkit artifacts, which require a much larger download.  CUDA_Compat_jll is only 10MB, so I'd prefer to use it whenever possible. What about making it a full-fledged Pkg dependency that gets downloaded when installing CUDA.jl?

**Comment by oschulz** [comment]
> whereas CUDA.jl generally prefers the most recent one possible (the Compat JLL gives a 11.4 driver)

Ah, I think I misunderstood the role of CUDA compat - you can pair a CUDA compat v11.4 with a CUDA 11.3 library stack?

**Comment by maleadt** [comment]
Yes, that should work. It only provides a newer driver interface.

**Comment by oschulz** [comment]
Neat, thanks. I added CUDA_compat_jll to the container and Julia system image, seems to work just fine!

**Comment by maleadt** [comment]
Great!
