### ISSUE TITLE
Artifacts.toml has bad git-tree-sha1 values

### ISSUE THREAD

**Issue by IanButterworth** [JuliaGPU/CUDA.jl#1309]
**Describe the bug**

It appears that the urls of the artifacts were updated in this commit but the git-tree-sha1 fields were not.

https://github.com/JuliaGPU/CUDA.jl/commit/10436614d8c69270dd73149102746d0b11cfbe3d#diff-1de81b882b140a45cfbcedd944f143a37759b544a9efc0f7008302578afa6360

This causes a rather confusing bug https://github.com/JuliaLang/Pkg.jl/issues/2929 where this appears on some systems depending on pkgserver usage.

```
 Downloading artifact: CUDA_compat
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   d9b5623143a996f924e7a5eee9d06354cb650d73
│   Calculated git-tree-sha1: b618eadab05abb3bef21da981a51b6f4f0183b27
└ @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:368
```

**To reproduce**

See https://github.com/JuliaLang/Pkg.jl/issues/2929

**Comment by maleadt** [comment]
That's weird, thanks for debugging.

I normally just copy over the Artifacts.toml contents from CUDA_loader_jll, so the same issue exists there as well (IIUC): https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/commit/ecb51de22e7681fc18bf6e7b58f5df0c05f9d9eb#diff-1de81b882b140a45cfbcedd944f143a37759b544a9efc0f7008302578afa6360. That Artifacts.toml is generated by BinaryBuilder; I didn't edit it. So something else is broken, too?

EDIT: or is this only problematic for CUDA_compat? I did appear to have badly copied those changes over: https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl/commit/bd512f429381c57f88183fbd97a7f4d10fd5df03. Maybe the fact that some tree hashes didn't change in CUDA_loader_jll is unrelated then (it's possible, since it always repackages old versions too whose contents shouldn't change).

**Comment by giordano** [comment]
https://github.com/JuliaGPU/CUDA.jl/pull/1234#discussion_r780558326

**Comment by maleadt** [comment]
Yes, but that's exactly why I also linked to [JuliaBinaryWrappers/CUDA_loader_jll.jl@ecb51de#diff-1de81b882b140a45cfbcedd944f143a37759b544a9efc0f7008302578afa6360](https://github.com/JuliaBinaryWrappers/CUDA_loader_jll.jl/commit/ecb51de22e7681fc18bf6e7b58f5df0c05f9d9eb#diff-1de81b882b140a45cfbcedd944f143a37759b544a9efc0f7008302578afa6360); the git tree sha's didn't change there.

**Comment by giordano** [comment]
They did at least for cuda_compat: https://github.com/JuliaBinaryWrappers/CUDA_compat_jll.jl/commit/bd512f429381c57f88183fbd97a7f4d10fd5df03#diff-1de81b882b140a45cfbcedd944f143a37759b544a9efc0f7008302578afa6360. See the diff of the first git-tree-sha1, they are the expected and computed hashes in the error message shown above

**Comment by maleadt** [comment]
Yes, I realized I copied those over badly, https://github.com/JuliaGPU/CUDA.jl/pull/1182#discussion_r780645835 :slightly_smiling_face: Thanks for debugging this!
