### ISSUE TITLE
NVTX: consider using Start/End for ranges

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#1485]
The problem with Push/Pop is that task switches can cause the wrong range to be popped. Start/End returns IDs so should be a better solution.

We probably also should be using the versions of these APIs that take objects instead of simple strings, so that we can customize the range more. https://github.com/simonbyrne/NVTX.jl has an initial implementation of that.

**Comment by simonbyrne** [comment]
Could we modify the CUDA.jl NVTX bindings so that we can use it without the CUDA driver being installed? I don't really understand the initialization stuff, so I'm not sure how easy that would be. Alternatively, I would be happy to register NVTX.jl, (I'd be happy to move it to JuliaGPU) and then CUDA.jl could depend on that?

**Comment by maleadt** [comment]
> Could we modify the CUDA.jl NVTX bindings so that we can use it without the CUDA driver being installed?

Well, I'm considering to make CUDA.jl initialize the CUDA driver at load time, pushing the burden of conditionally loading CUDA.jl on the user (which is reasonable now that we have Preferences.jl) so if that goes through the NVT change would be a short-lived feature.

I think @vchuravy or @jpsamaroo was also considering adding NVTX support to some vendor-neutral profile annotation library? Maybe that's a better approach?

**Comment by simonbyrne** [comment]
`NVTX.@range` uses start/end, so this can be closed.
