### ISSUE TITLE
Can we pleeeeeeeease make cu(x) eltype preserving?

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#278]
Automatically converting to Float32 is fraught with potential dangers for unexpecting users and it is not necessary or that useful. Julia users are used to being careful about their element types, and this design decision does not match the Julia spirit. Float32 is not that special and will be less so in the future: scientific applications may want Float64, many architectures, e.g. V100 supports it pretty well. A lot of new architectures support Float16 and deep learning people are discovering nnets perform pretty well using Float8s. I want to use cu(x) -- it is short, it supports Adapt.jl etc. but I avoid it because of this one bad design decision.

**Comment by maleadt** [comment]
`cu` is bad, yes, and I've reduced its scope in the past already. That often turned out hugely breaking (e.g., with users using functions that are only defined for Float32), so I'm not inclined to extend that to dropping the `Float32` conversion.

Would be happy to create an alternative function that does not do the conversion. Or better yet, have `adapt(CuArray, x)` work without conversion (which isn't terribly hard to type). Thoughts?

**Comment by denizyuret** [comment]
Makes sense. I am indifferent between the alternative function or the `adapt` solution, as long as there is a concise way to move arrays and structs to gpu without changing the eltype.
