### ISSUE TITLE
Performance: elementwise operations

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#307]
The following operations take about 7us with KnetArrays vs 10us with CuArrays for a (10,784) Float32 array. This slows down e.g. Adam updates during network training. There is no performance difference in `axpy!` (about 5us in both) probably because they both call the CUBLAS library function.
```
lmul!(2,a)
a .+ 2
a .* 2
a ./ 2
a .- 2
sqrt.(a)
a ./ a
```

**Comment by maleadt** [comment]
Did you test with latest master? Because these are broadcasts, which should have been improved with https://github.com/JuliaGPU/CUDA.jl/pull/299

**Comment by denizyuret** [comment]
Yes, I have the latest master. Knet ccalls a custom kernel, CuArray may have other overheads?
5d5ebab 2020-07-22

**Comment by maleadt** [comment]
Looking at just `lmul!`, the cause is call overhead. Knet only takes 2us, CUDA about 7, before the lmul kernel is launched. It's expected the costs are slightly higher because CUDA.jl does much more management (of handles, threads, etc) where Knet cuts some corners, but I'll have a look whether we can reduce those overheads a little.
