### ISSUE TITLE
Type changing Array conversions give error when allowscalar(false)

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#344]
```
a = CuArray([1.0, 2.0, 3.0])
convert(Array{Int32}, a) #-> tries slow scalar method
```
Here is a possible fix:
```
import Base.convert                                                                                                                                                          
convert(::Type{Array{T}}, x::CuArray{S,N}) where {T,N,S} = convert(Array{T,N}, x)                                                                                            
convert(::Type{Array{T,N}}, x::CuArray{S,N}) where {T,N,S} = convert(Array{T,N},Array(x))                                                                                    
```

**Comment by maleadt** [comment]
We don't implement `convert` methods, but instead rely on Base's array constructors calling `copyto!`. And we don't have `copyto!(Array{T}, CuArray{U})` because that operation is costly, either on-device (first converting the CuArray elements) or on the host (finally converting the Array elements). That choice is up to the user. and the same applies to `convert`: IMO CUDA.jl isn't to decide whether to pre-convert the GPU array, or do it afterwards on the CPU. So I'm not inclined to add this.

**Comment by denizyuret** [comment]
I think having a suboptimal implementation that works is better than having
no implementation and throwing an error. We support this type of conversion
on other array types like sparse arrays, special matrices, subarrays etc.
We can benchmark to see if there is any significant difference in
converting on GPU vs CPU.
