### ISSUE TITLE
getindex(::CuArray, ::Adjoint, ::Colon) fails

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#345]
This is also true for other AbstractArray types, such as SubArray etc. All work if the index is converted to Array first.
```
a = CUDA.rand(3,4)
b = rand(1:3,2,2)
a[b,:] # works
a[b',:] # fails
a[view(b,1,:), :] # fails
```

**Comment by maleadt** [comment]
Looks like the indexing kernel expects the adjoint to be GPU compatible (here a CPU adjoint gets passed). We're pretty inconsistent though about supporting CPU vs GPU indices though, and we should probably not implement `Base._unsafe_getindex` but just `getindex` so that we can handle all cases. This functionality would need to live in GPUArrays.jl.

**Comment by AliMalik9599** [comment]
Hi @maleadt I am interested in working on this issue. I am relatively new to Julia, any advice on starting? Thanks!

**Comment by maleadt** [comment]
Have a look (e.g. following through with `@edit`) at the indexing kernel in GPUArrays.jl. It should be fixed up to be compatible with this CPU adoint, e.g., uploading it to the GPU first. It currently also implements `Base._unsafe_getindex`, which is an internal interface, so it might be better to tackle that code entirely instead of fixing this use case. This all might be tricky for somebody new to Julia though, feel free to reach out on Slack (helpdesk or GPU channel) if you run into issues :-)
