### ISSUE TITLE
Texture memory?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#46]
We would like to make use of the texture memory functionality for high-dimensional interpolations. @vchuravy said it would be easy 👍 .

**Comment by maleadt** [comment]
Sweet! I haven't taken a close look yet, but it's good to see that you can get there with plain `llvmcall`s.

Out of curiosity, why did you pick CBinding* over plain Clang.jl? I just yesterday made the CUDAdrv.jl wrappers autogenerated (using Clang.jl), so that should make it easier to do further experimentation: https://github.com/JuliaGPU/CUDAdrv.jl/pull/157
