### ISSUE TITLE
Use LazyArtifacts instead of Pkg

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#570]
> Warning: using Pkg instead of using LazyArtifacts is deprecated

https://github.com/JuliaLang/julia/pull/37844

**Comment by dangirsh** [comment]
FYI, this breaks the ability to use `master` on Julia 1.5. If that was intended, we should update the minimum Julia version in the README.

This was quite confusing, since `]dev CUDA` on Julia 1.5.3 gives an error about `LazyArtifacts` being unavailable. `]add LazyArtifacts` fails, since it's not a real package. Currently, Googling "julia LazyArtfiacts" doesn't help at all either.

**Comment by maleadt** [comment]
Yes, that was intended, because of other compiler changes. The `Project.toml` also reflects that, but you're right that the README doesn't yet.
