### ISSUE TITLE
Support for CUDA-capable GPU with compute capability 4.0 like GTX 1080

### ISSUE THREAD

**Issue by trollichon** [JuliaGPU/CUDA.jl#587]
**Consider support for GTX 1080 and other GPU with compute capability 4.0**

The current README.md states that  only "GPU with compute capability 5.0" are currently supported. Would it be technically possible to support older GPUs with compute capability 4.0 in future ? If not, could someone give some technical information why this is not possible ?

Thanks all for the great job on cuda and julia.

**Comment by maleadt** [comment]
A GTX 1080 has compute capability 6.1, so is fully supported. sm_40 is really old, so doesn't seem like a problematic requirement nowadays. And older versions of CUDA.jl do support devices below it.

The reason is that certain CUDA APIs (gemmex) and kernel features (shuffle, certain atomics) are only available on recent hardware, so it simplifies our implementation here.
