### ISSUE TITLE
Extend new RNG to Complex numbers & normal distributions

### ISSUE THREAD

**Issue by nickkeepfer** [JuliaGPU/CUDA.jl#726]
I am trying to generate a Wiener noise on the GPU which requires a complex value noise, I also require to work in double precision. The generation of such a noise seems currently impossible without support for ComplexF64 type.

**Comment by RobbeCeulemans** [comment]
I get the same error for type ComplexF32, so I don't think it is related to the double precision

**Comment by maleadt** [comment]
This now works:

```
julia> CUDA.rand(ComplexF32, 1)
1-element CuArray{ComplexF32, 1}:
 0.60832024f0 + 0.34425035f0im

julia> CUDA.rand(ComplexF64, 1)
1-element CuArray{ComplexF64, 1}:
 0.6419787518680106 + 0.8088343231938792im
```

It only works with the old GPUArrays-based RNG, and would be good to port to the new one from https://github.com/JuliaGPU/CUDA.jl/pull/788. From a quick glance, this needs two pieces:
- extend RandomNumbers.jl so that it supports generating Complex{T} (which I presume is trivial since it just needs to call rand twice)
- implement `Random.randn!` in CUDA.jl, which can be based on https://github.com/JuliaGPU/GPUArrays.jl/blob/7f8410a1147bfb25a552d8ab1ee85d74bf9ed6fa/src/host/random.jl#L94-L109

**Comment by maleadt** [comment]
Both now work with the new RNG.
